  public @@HTTP_METHOD_PREFIX@@@@METHOD_NAME@@(@@METHOD_PARAMS@@): Observable<@@METHOD_NAME_FIRST_UP@@> {
    const url: string = @@URL_PROP_NAME@@@@REPLACE_URL_PARAMS@@;@@CONVERT_TO_QUERY_PARAMS@@
    return this.httpClient.@@HTTP_METHOD@@<@@METHOD_NAME_FIRST_UP@@>(url@@HTTP_SERVICE_SECOND_PARAM@@)@@END_OF_METHOD@@
  }
